apiVersion: v1
kind: Pod
metadata:
  name: busybox1
  labels:
    app: busybox1-labelchange2
spec:
  containers:
  - image: busybox
    command:
      - sleep
      - "32"
    imagePullPolicy: IfNotPresent
    name: busybox
  restartPolicy: Always
  
